### ISSUE TITLE
Charset converter

### ISSUE THREAD

**Issue by shotap** [zbateson/mail-mime-parser#53]
Hi,
from time to time I get an error about the ```iconv()``` in ```CharsetConverter.php```   
the error looks like:
```
PHP Fatal error:  Uncaught Exception: Error writing to storage ErrorException: [ERR] iconv(): Wrong charset, conversion from `UTF-8^M
 <!DOCTYPE HTML>' to `UTF-8//TRANSLIT//IGNORE' is not allowed in /app/smtpd.walla.co.il/vendor/zbateson/mail-mime-parser/src/Stream/Helper/CharsetConverter.php on line 335 in /app/smtpd.walla.co.il/app/bootstrap.php:29
Stack trace:
#0 [internal function]: errHandle(8, 'iconv(): Wrong ...', '/app/smtpd.wall...', 335, Array)
#1 /app/smtpd.walla.co.il/vendor/zbateson/mail-mime-parser/src/Stream/Helper/CharsetConverter.php(335): iconv('UTF-8\r\n <!DOCTY...', 'UTF-8//TRANSLIT...', '\r\n<html lang="h...')
#2 /app/smtpd.walla.co.il/vendor/zbateson/mail-mime-parser/src/Stream/CharsetStreamFilter.php(48): ZBateson\MailMimeParser\Stream\Helper\CharsetConverter->convert('\r\n<html lang="h...')
#3 [internal function]: ZBateson\MailMimeParser\Stream\CharsetStreamFilter->filter(Resource id #23210, Resource id #23211, NULL, false)
#4 /app/smtpd.walla.co.il/vendor/zbateson/mail-mime-parser/src/Message/Writer/Mim in /app/smtpd.walla.co.il/src/Worker/Store.php on line 45
```
this is probably because of parsing issues, what can I do to fix it?
I think that it will be the best to add a validation in the ```findSupportedCharset``` function to check if the string contains UTF-8 and if so to set the charset to that

**Comment by zbateson** [comment]
Charset handling has evolved and been moved to zbateson/mb-wrapper.  Not sure if this is an issue in the latest version, feel free to reopen if this needs to be looked at more.
